"""finalized schema sem2

Revision ID: 5f45e1b6d7a1
Revises: 1339404178ce
Create Date: 2026-03-24 14:59:01.867754

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f45e1b6d7a1"
down_revision: Union[str, Sequence[str], None] = "1339404178ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "api_key",
        sa.Column(
            "token",
            sa.String(length=128),
            nullable=True,
            comment="Opaque API key token.",
        ),
    )
    op.execute(
        "UPDATE api_key SET token = 'legacy-key-' || id::text WHERE token IS NULL"
    )
    op.alter_column("api_key", "token", nullable=False)
    op.create_index(op.f("ix_api_key_token"), "api_key", ["token"], unique=True)

    op.add_column(
        "chat_history",
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
            comment="Full chat messages payload.",
        ),
    )
    op.add_column(
        "chat_history",
        sa.Column(
            "max_tokens",
            sa.Integer(),
            server_default=sa.text("100"),
            nullable=False,
            comment="LLM response length limit.",
        ),
    )
    op.add_column(
        "chat_history",
        sa.Column(
            "streamed",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
            comment="Was response streamed.",
        ),
    )
    op.add_column(
        "chat_history",
        sa.Column(
            "response_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
            comment="Extra generation metadata.",
        ),
    )
    op.add_column("chat_history", sa.Column("user_id", sa.UUID(), nullable=True))
    op.add_column("chat_history", sa.Column("api_key_id", sa.Integer(), nullable=True))
    op.add_column(
        "chat_history",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=False),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
            comment="Chat completion creation date.",
        ),
    )
    op.create_foreign_key(
        "fk_chat_history_user_id_user",
        "chat_history",
        "user",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_chat_history_api_key_id_api_key",
        "chat_history",
        "api_key",
        ["api_key_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_index(
        op.f("ix_chat_history_user_id"), "chat_history", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_history_api_key_id"), "chat_history", ["api_key_id"], unique=False
    )
    op.create_index(
        op.f("ix_chat_history_created_at"), "chat_history", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_chat_history_created_at"), table_name="chat_history")
    op.drop_index(op.f("ix_chat_history_api_key_id"), table_name="chat_history")
    op.drop_index(op.f("ix_chat_history_user_id"), table_name="chat_history")
    op.drop_constraint(
        "fk_chat_history_api_key_id_api_key", "chat_history", type_="foreignkey"
    )
    op.drop_constraint(
        "fk_chat_history_user_id_user", "chat_history", type_="foreignkey"
    )
    op.drop_column("chat_history", "created_at")
    op.drop_column("chat_history", "api_key_id")
    op.drop_column("chat_history", "user_id")
    op.drop_column("chat_history", "response_metadata")
    op.drop_column("chat_history", "streamed")
    op.drop_column("chat_history", "max_tokens")
    op.drop_column("chat_history", "messages")
    op.drop_index(op.f("ix_api_key_token"), table_name="api_key")
    op.drop_column("api_key", "token")
    # ### end Alembic commands ###
