"""added chat_session

Revision ID: ee3365a2f00a
Revises: 5f45e1b6d7a1
Create Date: 2026-03-29 18:26:39.525398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee3365a2f00a'
down_revision: Union[str, Sequence[str], None] = '5f45e1b6d7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key.'),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('decision_makers_conference_people')
    op.drop_index(op.f('ix_decision_makers_achievement_id'), table_name='decision_makers_achievement')
    op.drop_table('decision_makers_achievement')
    op.drop_index(op.f('ix_decision_makers_employee_birthday_id'), table_name='decision_makers_employee_birthday')
    op.drop_table('decision_makers_employee_birthday')
    op.drop_index(op.f('ix_decision_makers_signal_id'), table_name='decision_makers_signal')
    op.drop_table('decision_makers_signal')
    op.drop_index(op.f('ix_decision_makers_appointment_id'), table_name='decision_makers_appointment')
    op.drop_table('decision_makers_appointment')
    op.drop_index(op.f('ix_decision_makers_person_id'), table_name='decision_makers_person')
    op.drop_table('decision_makers_person')
    op.drop_index(op.f('ix_global_article_mappings_table_global_id'), table_name='global_article_mappings_table')
    op.drop_table('global_article_mappings_table')
    op.drop_index(op.f('ix_decision_makers_professional_holiday_id'), table_name='decision_makers_professional_holiday')
    op.drop_table('decision_makers_professional_holiday')
    op.drop_index(op.f('ix_article_decision_makers_table_global_id'), table_name='article_decision_makers_table')
    op.drop_table('article_decision_makers_table')
    op.drop_index(op.f('ix_decision_makers_prcoessed_signals_id'), table_name='decision_makers_prcoessed_signals')
    op.drop_table('decision_makers_prcoessed_signals')
    op.drop_index(op.f('ix_decision_makers_company_birthday_id'), table_name='decision_makers_company_birthday')
    op.drop_table('decision_makers_company_birthday')
    op.drop_index(op.f('ix_parser_articles_table_url'), table_name='parser_articles_table')
    op.drop_table('parser_articles_table')
    op.drop_index(op.f('ix_dm_processed_table_global_id'), table_name='dm_processed_table')
    op.drop_table('dm_processed_table')
    op.drop_index(op.f('ix_decision_makers_holding_birthday_id'), table_name='decision_makers_holding_birthday')
    op.drop_table('decision_makers_holding_birthday')
    op.drop_table('prom_sent_dm_table')
    op.drop_table('decision_makers_conferences')
    op.drop_index(op.f('ix_decision_makers_organization_id'), table_name='decision_makers_organization')
    op.drop_table('decision_makers_organization')
    op.add_column('chat_history', sa.Column('session_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_chat_history_session_id'), 'chat_history', ['session_id'], unique=False)
    op.create_foreign_key(None, 'chat_history', 'chat_session', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='foreignkey')
    op.drop_index(op.f('ix_chat_history_session_id'), table_name='chat_history')
    op.drop_column('chat_history', 'session_id')
    op.create_table('decision_makers_organization',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('org_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_organization_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_organization_id'), 'decision_makers_organization', ['id'], unique=False)
    op.create_table('decision_makers_conferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('partners', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('subject', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_conferences_pkey'))
    )
    op.create_table('prom_sent_dm_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('dm_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('dm_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('send_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dm_id'], ['article_decision_makers_table.id'], name=op.f('prom_sent_dm_table_dm_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('prom_sent_dm_table_pkey'))
    )
    op.create_table('decision_makers_holding_birthday',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mentioned_org', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['signal_id'], ['decision_makers_signal.id'], name=op.f('decision_makers_holding_birthday_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_holding_birthday_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_holding_birthday_id'), 'decision_makers_holding_birthday', ['id'], unique=False)
    op.create_table('dm_processed_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('global_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['global_id'], ['global_article_mappings_table.global_id'], name=op.f('dm_processed_table_global_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('dm_processed_table_pkey'))
    )
    op.create_index(op.f('ix_dm_processed_table_global_id'), 'dm_processed_table', ['global_id'], unique=False)
    op.create_table('parser_articles_table',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ts_content', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('tags', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('duplicate', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('original_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('parsed_time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('parser_articles_table_pkey'))
    )
    op.create_index(op.f('ix_parser_articles_table_url'), 'parser_articles_table', ['url'], unique=False)
    op.create_table('decision_makers_company_birthday',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['decision_makers_organization.id'], name=op.f('decision_makers_company_birthday_company_id_fkey')),
    sa.ForeignKeyConstraint(['signal_id'], ['decision_makers_signal.id'], name=op.f('decision_makers_company_birthday_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_company_birthday_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_company_birthday_id'), 'decision_makers_company_birthday', ['id'], unique=False)
    op.create_table('decision_makers_prcoessed_signals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('global_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_processed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['global_id'], ['global_article_mappings_table.global_id'], name=op.f('decision_makers_prcoessed_signals_global_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_prcoessed_signals_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_prcoessed_signals_id'), 'decision_makers_prcoessed_signals', ['id'], unique=False)
    op.create_table('article_decision_makers_table',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('global_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_birth', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sentences', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('matched_company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dm_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['global_id'], ['global_article_mappings_table.global_id'], name=op.f('article_decision_makers_table_global_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('article_decision_makers_table_pkey'))
    )
    op.create_index(op.f('ix_article_decision_makers_table_global_id'), 'article_decision_makers_table', ['global_id'], unique=False)
    op.create_table('decision_makers_professional_holiday',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['decision_makers_organization.id'], name=op.f('decision_makers_professional_holiday_company_id_fkey')),
    sa.ForeignKeyConstraint(['signal_id'], ['decision_makers_signal.id'], name=op.f('decision_makers_professional_holiday_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_professional_holiday_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_professional_holiday_id'), 'decision_makers_professional_holiday', ['id'], unique=False)
    op.create_table('global_article_mappings_table',
    sa.Column('table_name', sa.VARCHAR(length=128), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('global_id', sa.BIGINT(), server_default=sa.text("nextval('global_article_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('global_id', name=op.f('global_article_mappings_table_pkey')),
    sa.UniqueConstraint('table_name', 'article_id', name=op.f('global_article_mappings_table_table_name_article_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_global_article_mappings_table_global_id'), 'global_article_mappings_table', ['global_id'], unique=True)
    op.create_table('decision_makers_person',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('holding_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('career_track', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['holding_id'], ['decision_makers_organization.id'], name=op.f('decision_makers_person_holding_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_person_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_person_id'), 'decision_makers_person', ['id'], unique=False)
    op.create_table('decision_makers_appointment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('prev_position', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['decision_makers_person.id'], name=op.f('decision_makers_appointment_person_id_fkey')),
    sa.ForeignKeyConstraint(['signal_id'], ['decision_makers_signal.id'], name=op.f('decision_makers_appointment_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_appointment_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_appointment_id'), 'decision_makers_appointment', ['id'], unique=False)
    op.create_table('decision_makers_signal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('holding_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('signal_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('day', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('not_parsed_date', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['global_article_mappings_table.global_id'], name=op.f('decision_makers_signal_article_id_fkey')),
    sa.ForeignKeyConstraint(['holding_id'], ['decision_makers_organization.id'], name=op.f('decision_makers_signal_holding_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_signal_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_signal_id'), 'decision_makers_signal', ['id'], unique=False)
    op.create_table('decision_makers_employee_birthday',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['decision_makers_person.id'], name=op.f('decision_makers_employee_birthday_person_id_fkey')),
    sa.ForeignKeyConstraint(['signal_id'], ['decision_makers_signal.id'], name=op.f('decision_makers_employee_birthday_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_employee_birthday_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_employee_birthday_id'), 'decision_makers_employee_birthday', ['id'], unique=False)
    op.create_table('decision_makers_achievement',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('result', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('result_importance', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['decision_makers_person.id'], name=op.f('decision_makers_achievement_person_id_fkey')),
    sa.ForeignKeyConstraint(['signal_id'], ['decision_makers_signal.id'], name=op.f('decision_makers_achievement_signal_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_achievement_pkey'))
    )
    op.create_index(op.f('ix_decision_makers_achievement_id'), 'decision_makers_achievement', ['id'], unique=False)
    op.create_table('decision_makers_conference_people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conf_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('full_name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('position', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('matched_company', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('date_birth', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('education', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.Column('career_track', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.Column('interest', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.Column('response_zone', sa.VARCHAR(length=4096), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conf_id'], ['decision_makers_conferences.id'], name=op.f('decision_makers_conference_people_conf_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('decision_makers_conference_people_pkey'))
    )
    op.drop_table('chat_session')
    # ### end Alembic commands ###
